// This file was generated by TemplateEngine from template source 'RecursiveSeries'
// using template 'RecursiveSeriesd. Do not modify this file directly, modify it from template source.

// This file constitutes a part of the SharpMedia project, (c) 2007 by the SharpMedia team
// and is licensed for your use under the conditions of the NDA or other legally binding contract
// that you or a legal entity you represent has signed with the SharpMedia team.
// In an event that you have received or obtained this file without such legally binding contract
// in place, you MUST destroy all files and other content to which this lincese applies and
// contact the SharpMedia team for further instructions at the internet mail address:
//
//    legal@sharpmedia.com
//
using System;
using System.Collections.Generic;
using System.Text;
using SharpMedia.AspectOriented;
using SharpMedia.Math.Functions.Discrete;

namespace SharpMedia.Math.Functions.Series
{

    /// <summary>
    /// A recursive series. Next value is computed from previous.
    /// </summary>
    public class RecusriveSeriesd : ISeriesd
    {
        #region Private Members
        double initial;
        Functiond f;
        #endregion

        #region Constructors

        public RecusriveSeriesd(double initial, [NotNull] Functiond f)
        {
            this.initial = initial;
            this.f = f;
        }

        #endregion

        #region ISeriesd Members

        public DiscreteFunctiond Function
        {
            get
            {
                return delegate(uint n)
                {
                    double v = initial;
                    for (int i = 1; i <= n; i++)
                    {
                        v = f(v);
                    }
                    return v;
                };

            }
        }

        public DiscreteFunctiond SumFunction
        {
            get
            {
                return delegate(uint n)
                {
                    double sum = initial;
                    double v = initial;
                    for (int i = 1; i <= n; i++)
                    {
                        v = f(v);
                        sum += v;
                    }
                    return sum;
                };
            }
        }

        public double[] Sample(uint begin, uint count)
        {
            double v = initial;
            for (int i = 1; i < begin; i++)
            {
                v = f(v);
            }

            // We go through all values.
            double[] results = new double[count];
            for (int j = 0; j < count; j++)
            {
                v = f(v);
                results[j] = v;
            }
            return results;
        }

        public double[] SampleSum(uint begin, uint count)
        {
            double v = initial, sum = 0; ;
            for (int i = 1; i < begin; i++)
            {
                v = f(v);
                sum += v;
            }

            // We go through all values.
            double[] results = new double[count];
            for (int j = 0; j < count; j++)
            {
                v = f(v);
                sum += v;
                results[j] = sum;
            }

            return results;
        }

        public double InfiniteSum
        {
            get { return double.NaN; }
        }

        #endregion
    }


}
