// This file was generated by TemplateEngine from template source 'Region3'
// using template 'Region3f. Do not modify this file directly, modify it from template source.

using System;
using System.Collections.Generic;
using System.Text;

namespace SharpMedia.Math
{
    /// <summary>
    /// A 3D region (box).
    /// </summary>
    public struct Region3f
    {
        #region Public Members
        /// <summary>
        /// Minimum coordinates (left, bottom, front).
        /// </summary>
        public Vector3f Minimum;

        /// <summary>
        /// Maximum coordinates (right, top, back).
        /// </summary>
        public Vector3f Maximum;
        #endregion

        #region Static Members

        /// <summary>
        /// A null region.
        /// </summary>
        public static Region3f Null
        {
            get
            {
                return new Region3f(Vector3f.Zero, Vector3f.Zero);
            }
        }

        /// <summary>
        /// Obtains a min-max range.
        /// </summary>
        /// <param name="points"></param>
        /// <returns></returns>
        public static Region3f MinMax(params Vector3f[] points)
        {
            if (points.Length == 0) return Null;

            Vector3f min = points[0];
            Vector3f max = points[0];

            for (int i = 1; i < points.Length; i++)
            {
                Vector3f v = points[i];

                min.X = min.X < v.X ? min.X : v.X;
                min.Y = min.Y < v.Y ? min.Y : v.Y;
                min.Z = min.Z < v.Z ? min.Z : v.Z;

                max.X = max.X > v.X ? max.X : v.X;
                max.Y = max.Y > v.Y ? max.Y : v.Y;
                max.Z = max.Z > v.Z ? max.Z : v.Z;
            }

            return new Region3f(min, max);
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the left front bottom coordinate.
        /// </summary>
        /// <value>The left bottom.</value>
        public Vector3f LeftFrontBottom
        {
            get { return Minimum; }
            set { Minimum = value; }
        }


        /// <summary>
        /// Gets or sets the right back top coordinate.
        /// </summary>
        /// <value>The right top.</value>
        public Vector3f RightBackTop
        {
            get { return Maximum; }
            set { Maximum = value; }
        }

        /// <summary>
        /// The width.
        /// </summary>
        public float Width
        {
            get { return Maximum.X - Minimum.X; }
        }

        /// <summary>
        /// The height.
        /// </summary>
        public float Height
        {
            get { return Maximum.Y - Minimum.Y; }
        }

        /// <summary>
        /// The depth.
        /// </summary>
        public float Depth
        {
            get { return Maximum.Z - Minimum.Z; }
        }


        /// <summary>
        /// The dimensions.
        /// </summary>
        public Vector3f Dimensions
        {
            get { return Maximum - Minimum; }
            set { Maximum = Minimum + value; }
        }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Region2i"/> class.
        /// </summary>
        public Region3f(Vector3f leftFrontBottom, Vector3f rightBackTop)
        {
            Minimum = leftFrontBottom;
            Maximum = rightBackTop;
        }

        #endregion
    }
}
