// This file was generated by TemplateEngine from template source 'Spherical'
// using template 'Sphericald. Do not modify this file directly, modify it from template source.

// This file constitutes a part of the SharpMedia project, (c) 2007 by the SharpMedia team
// and is licensed for your use under the conditions of the NDA or other legally binding contract
// that you or a legal entity you represent has signed with the SharpMedia team.
// In an event that you have received or obtained this file without such legally binding contract
// in place, you MUST destroy all files and other content to which this lincese applies and
// contact the SharpMedia team for further instructions at the internet mail address:
//
//    legal@sharpmedia.com
//
using System;
using System.Collections.Generic;
using System.Text;
using SharpMedia.Testing;

namespace SharpMedia.Math
{
    /// <summary>
    /// Spherical coordinate is defined by two angles and distance. It can
    /// be normalized, meaning that distance is 1.0. Spherical coordinates
    /// are useful for various applications, because sometimes it is easier
    /// to talk in terms of angles.
    /// </summary>
    [Serializable]
    public struct Sphericald : IEquatable<Sphericald>
    {
        #region Public Members

        /// <summary>
        /// Distance.
        /// </summary>
        public double R;

        /// <summary>
        /// Phi, angle between positive x if point is projected on x-y.
        /// </summary>
        public double Phi;

        /// <summary>
        /// Angle between positive z axis and vector that defines the point.
        /// </summary>
        public double Theta;

        #endregion

        #region Properties

        /// <summary>
        /// Normalized spherical.
        /// </summary>
        public Sphericald Normal
        {
            get { return new Sphericald(Phi, Theta); }
        }

        /// <summary>
        /// Length of coordinate.
        /// </summary>
        public double Length
        {
            get { return R; }
            set { R = value; }
        }

        /// <summary>
        /// Length of coordinate.
        /// </summary>
        public double Length2
        {
            get { return R*R; }
            //#ifdef Sqrt

            set { R = MathHelper.Sqrt(value); }
            //#endif
        }

        //#ifdef Vector3ClassName Sin Cos Atan


        /// <summary>
        /// Conversion to cartesian coordinate.
        /// </summary>
        public Vector3d Cartesian
        {
            get
            {
                double sint = MathHelper.Sin(Theta);
                double cost = MathHelper.Cos(Theta);
                double sinp = MathHelper.Sin(Phi);
                double cosp = MathHelper.Cos(Phi);

                return new Vector3d(R * sint * cosp,
                                    R * sint * sinp,
                                    R * cost);
            }
            set
            {

                // R is the length of the vector.
                this.R = value.Length;

                // We use atan2 because it will handle cases when x=0.
                Phi = MathHelper.ATan(value.Y, value.X);

                // The delta is this.
                Theta = MathHelper.ACos(value.Z / R);
            }
        }

        //#endif

        #endregion

        #region Overrides

        public override bool Equals(object obj)
        {
            if (obj is Sphericald)
            {
                return (Sphericald)obj == this;
            }
            return false;
        }

        public override int GetHashCode()
        {
            return Cartesian.GetHashCode();
        }

        public override string ToString()
        {
            StringBuilder b = new StringBuilder(30);
            b.Append("( ");
            b.Append(R);
            b.Append(", ");
            b.Append(Phi * 180.0 / global::System.Math.PI);
            b.Append("�, ");
            b.Append(Theta * 180.0 / global::System.Math.PI);
            b.Append("�)");
            return b.ToString();
        }

        #endregion

        #region Operators

        /// <summary>
        /// Compares two coordinates for identity.
        /// </summary>
        /// <param name="s1">The first spherical.</param>
        /// <param name="s2">The second spherical.</param>
        /// <returns>Are they equal</returns>
        public static bool operator ==(Sphericald s1, Sphericald s2)
        {
            return s1.Phi == s2.Phi && s1.R == s2.R && s1.Theta == s2.Theta;
        }

        /// <summary>
        /// Compares two coordinates for difference
        /// </summary>
        /// <param name="s1">The first spherical.</param>
        /// <param name="s2">The second spherical.</param>
        /// <returns>Are they not equal</returns>
        public static bool operator !=(Sphericald s1, Sphericald s2)
        {
            return !(s1 == s2);
        }

        #endregion

        #region Static Members

        //#ifdef NearEqual


        /// <summary>
        /// Near equal comparison.
        /// </summary>
        /// <param name="s1">The first spherical.</param>
        /// <param name="s2">The second spherical.</param>
        /// <returns>Are they nearly equal</returns>
        public static bool NearEqual(Sphericald s1, Sphericald s2)
        {
            return MathHelper.NearEqual(s1.Theta, s2.Theta) &&
                   MathHelper.NearEqual(s1.R, s2.R) &&
                   MathHelper.NearEqual(s1.Phi, s2.Phi);
        }

        /// <summary>
        /// Near equal comparison.
        /// </summary>
        /// <param name="s1">The first spherical.</param>
        /// <param name="s2">The second spherical.</param>
        /// <returns>Are they nearly equal</returns>
        public static bool NearEqual(Sphericald s1, Sphericald s2, double eps)
        {
            return MathHelper.NearEqual(s1.Theta, s2.Theta, eps) &&
                   MathHelper.NearEqual(s1.R, s2.R, eps) &&
                   MathHelper.NearEqual(s1.Phi, s2.Phi, eps);
        }

        //#endif

        /// <summary>
        /// A zero spherical.
        /// </summary>
        public static Sphericald Zero
        {
            get
            {
                return new Sphericald(0.0, 0.0, 0.0);
            }
        }

        

        /// <summary>
        /// A spherical interpolation.
        /// </summary>
        /// <param name="s1">The first coordinate.</param>
        /// <param name="s2">The second coordinate.</param>
        /// <param name="t">Value in range [0,1].</param>
        /// <returns>Spherical coordiante interpolated.</returns>
        public static Sphericald Interpolate(Sphericald s1, Sphericald s2, double t)
        {
            if (t < 0.0) t = 0.0;
            else if (t > 1.0) t = 1.0;

            double tm1 = 1.0 - t;
            return new Sphericald(s1.R * tm1 + s2.R * t,
                                  s1.Theta * tm1 + s2.Theta * t,
                                  s1.Phi * tm1 + s2.Phi * t);

        }


        #endregion

        #region Constructors

        /// <summary>
        /// Constructor with both angles and the radius.
        /// </summary>
        /// <param name="r">The radius.</param>
        /// <param name="Theta">Theta, z axis angle.</param>
        /// <param name="Phi">Phi angle.</param>
        public Sphericald(double r, double phi, double theta)
        {
            this.R = r;
            this.Theta = theta;
            this.Phi = phi;
        }

        /// <summary>
        /// Constructor with only angles, normalized.
        /// </summary>
        /// <param name="Theta">The Theta.</param>
        /// <param name="Phi">The Phi.</param>
        public Sphericald(double Phi, double Theta)
        {
            this.R = 1.0;
            this.Theta = Theta;
            this.Phi = Phi;
        }

        #endregion

        #region IEquatable<Sphericald> Members

        public bool Equals(Sphericald other)
        {
            return this == other;
        }

        #endregion

    }

#if SHARPMEDIA_TESTSUITE

    [TestSuite]
    internal class Test_Sphericald
    {
    /*
        [CorrectnessTest]
        public void Property()
        {
            Sphericald s = new Sphericald(MathHelper.ToRadians(60.0), MathHelper.ToRadians(30.0));
            Assert.IsTrue(MathHelper.NearEqual(MathHelper.ToRadians(60.0), s.Phi));
            Assert.IsTrue(MathHelper.NearEqual(MathHelper.ToRadians(30.0), s.Theta));
            Assert.AreEqual(1.0, s.R);
            Assert.AreEqual(1.0, s.Length);
            Assert.AreEqual(s, s.Normal);
        }

        [CorrectnessTest]
        public void Conv()
        {
            Vector3d v = new Vector3d(1.0, 1.0, 1.0);
            v = v.Normal;
            Sphericald s = v.Spherical;
            Assert.IsTrue(Vector3d.NearEqual(s.Cartesian, v));  
        }
    */
    }
#endif
}
