// This file was generated by TemplateEngine from template source 'MonteCarloIntegrator'
// using template 'MonteCarloIntegratord. Do not modify this file directly, modify it from template source.

using System;
using System.Collections.Generic;
using System.Text;
using SharpMedia.AspectOriented;

namespace SharpMedia.Math.Integration
{

    /// <summary>
    /// A monte-carlo integrator.
    /// </summary>
    public class MonteCarloIntegratord //:IIntegrator
    {

    }
}
