// This file was generated by TemplateEngine from template source 'CommonSteppers'
// using template 'CommonSteppersf. Do not modify this file directly, modify it from template source.

using System;
using System.Collections.Generic;
using System.Text;

namespace SharpMedia.Math.Interpolation
{
    /// <summary>
    /// A linear stepper.
    /// </summary>
    public class LinearStepperf : IUniformStepperf
    {
        public LinearStepperf()
        {
        }

        #region IUniformStepperf Members

        public float Interpolate(float t)
        {
            return t;
        }

        #endregion
    }

    /// <summary>
    /// A rational stepper, works as any polynomial stepper.
    /// </summary>
    public class RationalStepperf : IUniformStepperf
    {
        #region Private Members
        float power;
        #endregion

        #region Public Members

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <remarks>For square stepper, use power 0.5.</remarks>
        /// <param name="power"></param>
        public RationalStepperf(float power)
        {
            this.power = power;
        }

        #endregion

        #region IUniformStepperf Members

        public float Interpolate(float t)
        {
            return MathHelper.Pow(power, t);
        }

        #endregion
    }
}
