// This file was generated by TemplateEngine from template source 'PolynomialInterpolation'
// using template 'PolynomialInterpolation. Do not modify this file directly, modify it from template source.

using System;
using System.Collections.Generic;
using System.Text;

namespace SharpMedia.Math.Interpolation
{

    /// <summary>
    /// Provides rountines for various polynomial interpolations.
    /// </summary>
    public static class PolynomialInterpolation
    {
        

    }
}
