// This file was generated by TemplateEngine from template source 'Line'
// using template 'Line3d. Do not modify this file directly, modify it from template source.

// This file constitutes a part of the SharpMedia project, (c) 2007 by the SharpMedia team
// and is licensed for your use under the conditions of the NDA or other legally binding contract
// that you or a legal entity you represent has signed with the SharpMedia team.
// In an event that you have received or obtained this file without such legally binding contract
// in place, you MUST destroy all files and other content to which this lincese applies and
// contact the SharpMedia team for further instructions at the internet mail address:
//
//    legal@sharpmedia.com
//
using System;
using System.Collections.Generic;
using System.Text;
using SharpMedia.Testing;
using SharpMedia.AspectOriented;

namespace SharpMedia.Math.Shapes
{


    /// <summary>
    /// A line in 3D space. Line is determined by two points, A and B point.
    /// </summary>
    [Serializable]
    public sealed class Line3d :
        IOutline3d, IControlPoints3d, IContainsPoint3d, ITransformable3d,
        IEquatable<Line3d>, IComparable<Line3d>,
        IEnumerable<Vector3d>, ICloneable<Line3d>
    {

        #region Public Members

        /// <summary>
        /// The start control point.
        /// </summary>
        public Vector3d A;

        /// <summary>
        /// Ending control point.
        /// </summary>
        public Vector3d B;

        #endregion

        #region Constructors


        /// <summary>
        /// Empty contructor.
        /// </summary>
        public Line3d()
        {
        }

        /// <summary>
        /// Line constructor.
        /// </summary>
        /// <param name="from">From point.</param>
        /// <param name="to">To point.</param>
        public Line3d(Vector3d a, Vector3d b)
        {
            this.A = a;
            this.B = b;
        }

        /// <summary>
        /// Line constructor.
        /// </summary>
        /// <param name="from">From point.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="length">Length of line in direction.</param>
        public Line3d(Vector3d from, Vector3d direction, double length)
        {
            this.A = from;
            this.B = from + length * direction;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Are two lines parallel.
        /// </summary>
        /// <param name="other">The other line.</param>
        /// <returns>Are they parallel.</returns>
        public bool IsParallel([NotNull] Line3d other)
        {
            if (Vector3d.NearEqual(Direction, other.Direction)) return true;
            return false;
        }

        /// <summary>
        /// The lines are perpBicular.
        /// </summary>
        /// <param name="other">The other line.</param>
        /// <returns>Are lines perpBicular.</returns>
        public bool IsPerpendicular([NotNull] Line3d other)
        {
            Vector3d special;
            
            special = new Vector3d((double) - 1, (double) - 1, (double) - 1);
            

            return Vector3d.NearEqual(Direction,
                Vector3d.ComponentDivision(
                special, Direction));
        }

        /// <summary>
        /// Distance from one point.
        /// </summary>
        /// <param name="p">The point.</param>
        /// <returns>Distance.</returns>
        public double PointDistance(Vector3d p)
        {
            // The formula is:
            // d = |Direction x (A-p)| / |Direction|^2
            return (Direction ^ (A - p)).Length / Direction.Length2;
        }

        #endregion

        #region Properties

        /// <summary>
        /// The direction of line. It's length is always the length
        /// of line.
        /// </summary>
        public Vector3d Direction
        {
            get { return B - A; }
            set
            {
                B = A + value;
            }
        }

        /// <summary>
        /// A unit direction.
        /// </summary>
        public Vector3d UnitDirection
        {
            get { return Direction.Normal; }
            set
            {
                double l = Length;
                B = A + value * l;
            }
        }

        /// <summary>
        /// Length of line.
        /// </summary>
        public double Length
        {
            get { return (A - B).Length; }
            set
            {
                if (value < 0)
                {
                    throw new ArgumentException("Length cannot be negative");
                }
                else if (value == 0)
                {
                    B = A;
                }
                else if (Length != 0.0)
                {
                    // scaling
                    B = A + ((B - A) / Length * value);
                }
                else throw new Exception("Cannot scale zero-length lines (points)");
            }
        }

        #endregion

        #region Overrides

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder(60);
            builder.Append("LineSegment : {");
            builder.Append(A.ToString());
            builder.Append(", ");
            builder.Append(B.ToString());
            builder.Append("}");
            return builder.ToString();
        }

        public override bool Equals(object obj)
        {
            if (obj is Line3d) return this.Equals((Line3d)obj);
            return false;
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #endregion

        #region IContainsPoint3d Members

        public bool ContainsPoint(Vector3d p)
        {
            // We get direction of one and direction of second.
            Vector3d x = p - A;

            // If p is the same as control.
            if (x.Length2 == 0.0) return true;

            if (!Vector3d.NearEqual(x.Normal, Direction.Normal)) return false;
            double t = x.Length2 / Direction.Length2;
            return t >= 0.0 && t <= 1.0;
        }

        #endregion

        #region IOutline3d Members

        public Vector3d Sample(double t)
        {
            return (1.0 - t) * A + t * B;
        }

        public void Sample(double resolution, Storage.Builders.ILineBuilder3d builder)
        {
            if (resolution < 0.0)
            {
                builder.AddLineStrip(false, A, B);
            }
            else
            {
                throw new NotImplementedException();
            }
        }

        #endregion

        #region IOutlined Members

        public double OutlineLength
        {
            get { return (B - A).Length; }
        }

        #endregion

        #region IControlPoints3d Members

        public Vector3d[] ControlPoints
        {
            get
            {
                return new Vector3d[] { A, B };
            }
            set
            {
                if (value.Length != 2) throw new ArgumentException("Two control points expected.");
                A = value[0];
                B = value[1];
            }
        }

        public void SetControlPoints(uint index, Vector3d cp)
        {
            switch (index)
            {
                case 0:
                    A = cp;
                    break;
                case 1:
                    B = cp;
                    break;
                default:
                    throw new ArgumentException("Index out of range, must be 0-1 for line segment.");
            }
        }

        public Vector3d GetControlPoint(uint index)
        {
            switch (index)
            {
                case 0:
                    return A;
                case 1:
                    return B;
                default:
                    throw new ArgumentException("Index out of range, must be 0-1 for line segment.");
            }
        }

        #endregion

        #region IControlPointsd Members

        public uint ControlPointCount
        {
            get { return 2; }
        }

        #endregion

        #region ITransformable3d

        public void Transform(Matrix.Matrix4x4d matrix)
        {
            A = matrix * A;
            B = matrix * B;
        }

        #endregion

        #region ICloneable<Line3d> Members

        public Line3d Clone()
        {
            return new Line3d(A, B);
        }

        #endregion

        #region IEquatable<Line3d> Members

        public bool Equals(Line3d other)
        {
            if (Vector3d.NearEqual(this.Direction, other.Direction) &&
                this.ContainsPoint(other.A)) return true;
            return false;
        }
        #endregion

        #region IComparable<ClassName> Members

        public int CompareTo(Line3d other)
        {
            int cmp = A.CompareTo(other.A);
            if (cmp != 0) return cmp;
            return B.CompareTo(other.B);

        }

        #endregion

        #region IEnumerable<Vector3d> Members

        public IEnumerator<Vector3d> GetEnumerator()
        {
            yield return A;
            yield return B;
        }

        #endregion

        #region IEnumerable Members

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            yield return A;
            yield return B;
        }

        #endregion
    }

#if SHARPMEDIA_TESTSUITE
    [TestSuite]
    internal class Line3d_Test
    {
        /*
        [CorrectnessTest]
        public void LineConstruction()
        {
            Line3d line1 = new Line3d(new Vector3d(0, 0, 0), new Vector3d(3, 3, 3));
            Line3d line2 = new Line3d(new Vector3d(0, 0, 0), new Vector3d(1, 1, 1), 3.0);

            Assert.IsTrue(line1.Equals(line1));
            Assert.IsTrue(line2.Equals(line2));
            Assert.IsTrue(line1.Equals(line2));
        }

        [CorrectnessTest]
        public void Properties()
        {
            Line3d line1 = new Line3d(new Vector3d(0, 0, 0), new Vector3d(2, 0, 0));
            Assert.AreEqual(2.0, line1.Length);
            Assert.AreEqual(1, line1.LineSegmentCount);
            Assert.AreEqual(1, line1.Lines.Length);
            Assert.AreEqual(line1.UnitDirection, new Vector3d(1, 0, 0));
        }

        [CorrectnessTest]
        public void Contains()
        {
            Line3d line = new Line3d(new Vector3d(1, 0, 0), new Vector3d(2, 1, 0));
            Assert.IsTrue(line.ContainsPoint(new Vector3d(1.5, 0.5, 0)));
        }

        [CorrectnessTest]
        public void Intersection()
        {
            Line3d line1 = new Line3d(new Vector3d(0, 0, 0), new Vector3d(3, 0, 0));
            Line3d line2 = new Line3d(new Vector3d(1, -1, 0), new Vector3d(1, 5, 0));

            Assert.IsTrue(line1.IntersectsWith(line2));
            Pointd p = (Pointd)line1.Intersection(line2)[0];
            Assert.AreEqual(new Pointd(1, 0, 0), p);
        }*/
    }
#endif
}
