// This file constitutes a part of the SharpMedia project, (c) 2007 by the SharpMedia team
// and is licensed for your use under the conditions of the NDA or other legally binding contract
// that you or a legal entity you represent has signed with the SharpMedia team.
// In an event that you have received or obtained this file without such legally binding contract
// in place, you MUST destroy all files and other content to which this lincese applies and
// contact the SharpMedia team for further instructions at the internet mail address:
//
//    legal@sharpmedia.com
//
using System;
using System.Collections.Generic;
using System.Text;

namespace SharpMedia.Input
{
    /// <summary>
    /// Key Codes, an array of 256 values.
    /// </summary>
    public enum KeyCodes : byte
    {
        Unknown = 0,
        Key0 = 1,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
        KeyA,
        ABNT_C1,
        ABNT_C2,
        ADD,
        APOSTROPHE,
        APPS,
        AT,
        AX,
        B,
        BACK,
        BACKSLASH,
        C,
        CALCULATOR,
        CAPITAL,
        COLON,
        COMMA,
        CONVERT,
        D,
        DECIMAL,
        DELETE,
        DIVIDE,
        DOWN,
        E,
        END,
        EQUALS,
        ESCAPE,
        F,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        G,
        GRAVE,
        H,
        HOME,
        I,
        INSERT,
        J,
        K,
        KANA,
        KANJI,
        L,
        LBRACKET,
        LCONTROL,
        LEFT,
        LMENU,
        LSHIFT,
        LWIN,
        M,
        MAIL,
        MEDIASELECT,
        MEDIASTOP,
        MINUS,
        MULTIPLY,
        MUTE,
        MYCOMPUTER,
        N,
        NEXT,
        NEXTTRACK,
        NOCONVERT,
        NUMLOCK,
        NUMPAD0,
        NUMPAD1,
        NUMPAD2,
        NUMPAD3,
        NUMPAD4,
        NUMPAD5,
        NUMPAD6,
        NUMPAD7,
        NUMPAD8,
        NUMPAD9,
        NUMPADCOMMA,
        NUMPADENTER,
        NUMPADEQUALS,
        O,
        OEM_102,
        P,
        PAUSE,
        PERIOD,
        PLAYPAUSE,
        POWER,
        PREVTRACK,
        PRIOR,
        Q,
        R,
        RBRACKET,
        RCONTROL,
        RETURN,
        RIGHT,
        RMENU,
        RSHIFT,
        RWIN,
        S,
        SCROLL,
        SEMICOLON,
        SLASH,
        SLEEP,
        SPACE,
        STOP,
        SUBTRACT,
        SYSRQ,
        T,
        TAB,
        U,
        UNDERLINE,
        UNLABELED,
        UP,
        V,
        VOLUMEDOWN,
        VOLUMEUP,
        W,
        WAKE,
        WEBBACK,
        WEBFAVORITES,
        WEBFORWARD,
        WEBHOME,
        WEBREFRESH,
        WEBSEARCH,
        WEBSTOP,
        X,
        Y,
        YEN,
        Z
    }
}
